# hyprpaper.conf

# preload the image into memory first (required before setting wallpaper)
preload = /home/giyu/Pictures/Wallpapers/NixOS.png

# set wallpaper per monitor
# format: wallpaper = <monitor>,<path>
# use "," (empty monitor name) to apply to ALL monitors
wallpaper = eDP-1,/home/giyu/Pictures/Wallpapers/NixOS.png

# optional: hide the IPC socket (slightly better perf, but you can't use hyprctl hyprpaper)
# ipc = off

# optional: splash text (the "hyprpaper" text on startup)
splash = false
