# Preload wallpapers (loads into memory)
preload = ~/Pictures/Wallpapers/Lofi-Cafe1.png
preload = ~/Pictures/Wallpapers/Lofi-Cafe2.png
preload = ~/Pictures/Wallpapers/Video Game - The Blackstreets.jpeg

# Set wallpaper for specific monitor
# Find monitor name with: hyprctl monitors
wallpaper = ,~/Pictures/Wallpapers/Lofi-Cafe1.png

# Enable splash text rendering
splash = false

# Enable IPC for changing wallpapers on-the-fly
ipc = on
